const SUPABASE_URL='https://kdfbxcdxdhofqidczbot.supabase.co';
const SUPABASE_KEY='sb_publishable_51lY0ST_vE6v0nogH5RGkQ_z8lJ5EAM';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let user=null,authMode='login',lastWaterLog=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2200)}
function localDayStart(){const d=new Date();d.setHours(0,0,0,0);return d.toISOString()}
function fmtDate(v){if(!v)return 'بدون موعد';return new Date(v).toLocaleString('ar-EG',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function showPage(page){document.querySelectorAll('[id^="page-"]').forEach(s=>s.classList.add('hidden'));$('page-'+page).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));refreshAll()}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
$('todayDate').textContent=new Date().toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long'});
$('loginTab').onclick=()=>{authMode='login';$('loginTab').classList.add('active');$('signupTab').classList.remove('active');$('authSubmit').textContent='دخول'};
$('signupTab').onclick=()=>{authMode='signup';$('signupTab').classList.add('active');$('loginTab').classList.remove('active');$('authSubmit').textContent='إنشاء الحساب'};
$('authSubmit').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6){$('authMsg').textContent='اكتب إيميل صحيح وباسورد 6 حروف على الأقل.';return}$('authMsg').textContent='جاري...';const result=authMode==='signup'?await sb.auth.signUp({email,password,options:{data:{display_name:'Serag'}}}):await sb.auth.signInWithPassword({email,password});if(result.error){$('authMsg').textContent=result.error.message;return}$('authMsg').textContent=authMode==='signup'?'اتعمل الحساب. لو وصلك تأكيد إيميل، أكده وبعدها ادخل.':'تم تسجيل الدخول.'};
$('logoutBtn').onclick=()=>sb.auth.signOut();$('refreshBtn').onclick=()=>refreshAll();
sb.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;$('authView').classList.toggle('hidden',!!user);$('appView').classList.toggle('hidden',!user);if(user)refreshAll()});
async function loadWater(){const {data=[],error}=await sb.from('water_logs').select('*').gte('logged_at',localDayStart()).order('logged_at',{ascending:true});if(error)return;lastWaterLog=data.at(-1)?.id||null;const ml=data.reduce((a,x)=>a+(x.amount_ml||0),0);const cups=Math.round(ml/250);$('waterCount').textContent=cups;$('homeWater').textContent=cups;$('homeWaterBar').style.width=Math.min(100,cups/8*100)+'%';$('waterCups').innerHTML=Array.from({length:8},(_,i)=>`<div class="cup ${i<cups?'done':''}">💧</div>`).join('');return cups}
$('addWater').onclick=async()=>{const {error}=await sb.from('water_logs').insert({user_id:user.id,amount_ml:250});if(error)return toast(error.message);toast('اتسجل كوب مياه 💧');loadWater();loadHomeTip()};
$('undoWater').onclick=async()=>{if(!lastWaterLog)return toast('مفيش كوب تتراجع عنه');await sb.from('water_logs').delete().eq('id',lastWaterLog);toast('اتشال آخر كوب');loadWater();loadHomeTip()};
$('mealForm').onsubmit=async e=>{e.preventDefault();const name=$('mealName').value.trim();const {error}=await sb.from('meals').insert({user_id:user.id,name,calories:Number($('mealCalories').value)||0,protein_g:Number($('mealProtein').value)||0});if(error)return toast(error.message);e.target.reset();toast('الوجبة اتحفظت');loadMeals();loadHomeTip()};
async function loadMeals(){const {data=[],error}=await sb.from('meals').select('*').gte('eaten_at',localDayStart()).order('eaten_at',{ascending:false});if(error)return;$('mealsList').innerHTML=data.length?data.map(x=>`<div class="row"><div><div class="row-title">${esc(x.name)}</div><div class="row-meta">${Number(x.protein_g||0)}g protein</div></div><span class="pill">${x.calories||0} kcal</span></div>`).join(''):'<div class="empty">لسه مفيش وجبات مسجلة.</div>';const calories=data.reduce((a,x)=>a+(x.calories||0),0);$('homeCalories').textContent=calories;$('homeCaloriesBar').style.width=Math.min(100,calories/2800*100)+'%';return calories}
$('workoutForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('workouts').insert({user_id:user.id,title:$('workoutTitle').value.trim(),notes:$('workoutNotes').value.trim(),exercises:[]});if(error)return toast(error.message);e.target.reset();toast('التمرين اتحفظ');loadWorkouts()};
async function loadWorkouts(){const {data=[]}=await sb.from('workouts').select('*').order('workout_date',{ascending:false}).limit(5);$('workoutsList').innerHTML=data.length?data.map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.notes||'')}</div></div><span class="pill">${x.workout_date}</span></div>`).join(''):'<div class="empty">لسه مفيش تمرين مسجل.</div>'}
$('taskForm').onsubmit=async e=>{e.preventDefault();const due=$('taskDue').value?new Date($('taskDue').value).toISOString():null;const {error}=await sb.from('tasks').insert({user_id:user.id,title:$('taskTitle').value.trim(),category:$('taskCategory').value,due_at:due,priority:$('taskPriority').value});if(error)return toast(error.message);e.target.reset();toast('المهمة اتضافت');loadTasks()};
async function loadTasks(){const {data=[],error}=await sb.from('tasks').select('*').neq('status','done').order('due_at',{ascending:true,nullsFirst:false});if(error)return;const render=x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.category)} · ${fmtDate(x.due_at)} · ${esc(x.priority)}</div></div><button class="btn doneTask" data-id="${x.id}" type="button">تم</button></div>`;$('tasksList').innerHTML=data.length?data.map(render).join(''):'<div class="empty">مفيش مهام مفتوحة.</div>';$('homeTaskList').innerHTML=data.length?data.slice(0,5).map(render).join(''):'<div class="empty">الدنيا فاضية ✨</div>';$('homeTasks').textContent=data.length;const work=data.filter(x=>x.category==='work');$('workTaskList').innerHTML=work.length?work.map(render).join(''):'<div class="empty">مفيش مهام شغل.</div>';document.querySelectorAll('.doneTask').forEach(b=>b.onclick=async()=>{await sb.from('tasks').update({status:'done'}).eq('id',b.dataset.id);toast('تمام ✓');loadTasks()})}
$('wordForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('english_words').insert({user_id:user.id,word:$('newWord').value.trim(),meaning:$('wordMeaning').value.trim(),example:$('wordExample').value.trim()});if(error)return toast(error.message);e.target.reset();toast('الكلمة اتحفظت');loadEnglish()};
$('grammarForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('grammar_topics').insert({user_id:user.id,title:$('grammarTitle').value.trim(),notes:$('grammarNotes').value.trim()});if(error)return toast(error.message);e.target.reset();loadEnglish()};
$('englishCourseForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('courses').insert({user_id:user.id,title:$('englishCourseTitle').value.trim(),url:$('englishCourseUrl').value.trim(),progress:Number($('englishCourseProgress').value)||0,category:'english',status:'active'});if(error)return toast(error.message);e.target.reset();loadEnglish()};
$('writingForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('english_writing').insert({user_id:user.id,title:$('writingTitle').value.trim(),content:$('writingContent').value.trim()});if(error)return toast(error.message);e.target.reset();toast('الكتابة اتحفظت');loadEnglish()};
async function loadEnglish(){const [w,g,c,wr]=await Promise.all([sb.from('english_words').select('*').order('created_at',{ascending:false}).limit(20),sb.from('grammar_topics').select('*').order('created_at',{ascending:false}).limit(20),sb.from('courses').select('*').eq('category','english').order('created_at',{ascending:false}).limit(20),sb.from('english_writing').select('*').order('created_at',{ascending:false}).limit(10)]);$('wordsList').innerHTML=(w.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.word)}</div><div class="row-meta">${esc(x.meaning||'')}${x.example?' · '+esc(x.example):''}</div></div><span class="pill">${esc(x.status)}</span></div>`).join('')||'<div class="empty">ابدأ بأول كلمة جديدة.</div>';$('grammarList').innerHTML=(g.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.notes||'')}</div></div><span class="pill">${esc(x.status)}</span></div>`).join('')||'<div class="empty">لسه مفيش قواعد.</div>';$('englishCoursesList').innerHTML=(c.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${x.url?`<a class="link" target="_blank" rel="noopener" href="${esc(x.url)}">فتح الكورس</a>`:''}</div></div><span class="pill">${x.progress||0}%</span></div>`).join('')||'<div class="empty">ضيف الكورس اللي هتبدأه.</div>';$('writingList').innerHTML=(wr.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title||'Writing')}</div><div class="row-meta">${esc((x.content||'').slice(0,90))}</div></div></div>`).join('')||'<div class="empty">مفيش Writing محفوظ لسه.</div>'}
$('projectForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('creative_projects').insert({user_id:user.id,title:$('projectTitle').value.trim(),project_type:$('projectType').value.trim(),brief:$('projectBrief').value.trim()});if(error)return toast(error.message);e.target.reset();toast('المشروع اتضاف');loadCreative()};
$('resourceForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('creative_resources').insert({user_id:user.id,title:$('resourceTitle').value.trim(),url:$('resourceUrl').value.trim(),resource_type:$('resourceType').value.trim()||'reference'});if(error)return toast(error.message);e.target.reset();toast('المصدر اتحفظ');loadCreative()};
$('creativeCourseForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('courses').insert({user_id:user.id,title:$('creativeCourseTitle').value.trim(),url:$('creativeCourseUrl').value.trim(),progress:Number($('creativeCourseProgress').value)||0,category:'creative',status:'saved'});if(error)return toast(error.message);e.target.reset();loadCreative()};
async function loadCreative(){const [p,r,c]=await Promise.all([sb.from('creative_projects').select('*').order('created_at',{ascending:false}).limit(20),sb.from('creative_resources').select('*').order('created_at',{ascending:false}).limit(30),sb.from('courses').select('*').eq('category','creative').order('created_at',{ascending:false}).limit(20)]);$('projectsList').innerHTML=(p.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.project_type||'')} · ${esc((x.brief||'').slice(0,70))}</div></div><span class="pill">${esc(x.status)}</span></div>`).join('')||'<div class="empty">مفيش مشاريع كريتف لسه.</div>';$('resourcesList').innerHTML=(r.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.resource_type||'reference')}</div></div>${x.url?`<a class="btn" target="_blank" rel="noopener" href="${esc(x.url)}">فتح</a>`:''}</div>`).join('')||'<div class="empty">ضيف أول موقع Reference.</div>';$('creativeCoursesList').innerHTML=(c.data||[]).map(x=>`<div class="row"><div><div class="row-title">${esc(x.title)}</div><div class="row-meta">${x.url?`<a class="link" target="_blank" rel="noopener" href="${esc(x.url)}">فتح الكورس</a>`:''}</div></div><span class="pill">${x.progress||0}%</span></div>`).join('')||'<div class="empty">لسه مفيش كورسات كريتف.</div>'}
$('assistantSend').onclick=async()=>{const q=$('assistantPrompt').value.trim();if(!q)return;const a=$('assistantAnswer');a.classList.remove('hidden');a.textContent='جاري التفكير...';$('assistantSend').disabled=true;try{const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('سجل دخول الأول');const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({message:q,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});const data=await r.json();if(!r.ok)throw new Error(data.error||'حصل خطأ');a.textContent=data.answer||'تم.';$('assistantPrompt').value='';await refreshAll()}catch(err){a.textContent='حصلت مشكلة: '+err.message}finally{$('assistantSend').disabled=false}};
async function loadHomeTip(){const [cups,calories]=await Promise.all([loadWater(),loadMeals()]);let tip='الدنيا ماشية كويس.';if((cups||0)<3)tip='المياه قليلة لحد دلوقتي. حاول تشرب كوب دلوقتي وتكمل على فترات.';else if((calories||0)<1200)tip='الأكل لسه قليل مقارنة بهدف اليوم. سجّل الوجبة الجاية علشان نتابع بشكل أدق.';$('homeTip').textContent=tip}
async function refreshAll(){if(!user)return;await Promise.all([loadWater(),loadMeals(),loadWorkouts(),loadTasks(),loadEnglish(),loadCreative()]);loadHomeTip()}
function installAssistantUI(){const n=document.querySelector('#page-creative .notice');if(n)n.textContent='المساعد متصل بـ OpenAI ويقدر يقرأ بيانات Serag OS وينفّذ أوامر زي إضافة مهام ووجبات ومياه وكورسات ومشاريع.';const link=document.createElement('a');link.href='/assistant.html';link.textContent='✦ المساعد';link.setAttribute('aria-label','فتح المساعد الذكي');Object.assign(link.style,{position:'fixed',left:'18px',bottom:'18px',zIndex:'9',background:'#7058e8',color:'#fff',textDecoration:'none',padding:'11px 15px',borderRadius:'999px',fontWeight:'800',fontSize:'13px',boxShadow:'0 8px 24px #0002'});document.body.appendChild(link)}
(async()=>{const {data:{session}}=await sb.auth.getSession();user=session?.user||null;$('authView').classList.toggle('hidden',!!user);$('appView').classList.toggle('hidden',!user);if(user)refreshAll();installAssistantUI();if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(()=>{})}})();